Description: "Cloudformation Hook Execution Role" 
Resources:
  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'cft-hook-exec-role-${AWS::AccountId}-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - resources.cloudformation.amazonaws.com
                - hooks.cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CftHooksDenyAllPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'